WIP for Pawel

diff --git a/recipes-dbs/postgresql/files/postgresql-setup b/recipes-dbs/postgresql/files/postgresql-setup
--- a/recipes-dbs/postgresql/files/postgresql-setup
+++ b/recipes-dbs/postgresql/files/postgresql-setup
@@ -18,57 +18,105 @@ script_result=0
 initdb(){
     if [ -f "$PGDATA/PG_VERSION" ]
     then
-	echo -n "Data directory is not empty!"
-	echo -n " [FAILED] "
-	echo
-	script_result=1
+    echo -n "Data directory is not empty!"
+    echo -n " [FAILED] "
+    echo
+    script_result=1
     else
-	echo -n  -n "Initializing database: "
-	if [ ! -e "$PGDATA" -a ! -h "$PGDATA" ]
-	then
-		mkdir -p "$PGDATA" || exit 1
-		chown postgres:postgres "$PGDATA"
-		chmod go-rwx "$PGDATA"
-	fi
-	echo -n  Clean up SELinux tagging for PGDATA
-	[ -x /sbin/restorecon ] && /sbin/restorecon "$PGDATA"
+    echo -n  -n "Initializing database: "
+    if [ ! -e "$PGDATA" -a ! -h "$PGDATA" ]
+    then
+        mkdir -p "$PGDATA" || exit 1
+        chown postgres:postgres "$PGDATA"
+        chmod go-rwx "$PGDATA"
+    fi
+    echo -n  Clean up SELinux tagging for PGDATA
+    [ -x /sbin/restorecon ] && /sbin/restorecon "$PGDATA"
 
-	echo -n  Make sure the startup-time log file is OK, too
-	if [ ! -e "$PGLOG" -a ! -h "$PGLOG" ]
-	then
-		touch "$PGLOG" || exit 1
-		chown postgres:postgres "$PGLOG"
-		chmod go-rwx "$PGLOG"
-		[ -x /sbin/restorecon ] && /sbin/restorecon "$PGLOG"
-	fi
+    echo -n  Make sure the startup-time log file is OK, too
+    if [ ! -e "$PGLOG" -a ! -h "$PGLOG" ]
+    then
+        touch "$PGLOG" || exit 1
+        chown postgres:postgres "$PGLOG"
+        chmod go-rwx "$PGLOG"
+        [ -x /sbin/restorecon ] && /sbin/restorecon "$PGLOG"
+    fi
 
-	echo -n  Initialize the database
-	$SU -l postgres -c "$PGENGINE/initdb --pgdata='$PGDATA' --auth='ident'" >> "$PGLOG" 2>&1 < /dev/null
+    echo -n  Initialize the database
+    $SU -l postgres -c "$PGENGINE/initdb -d --pgdata='$PGDATA' --auth='ident'" >> "$PGLOG" 2>&1 < /dev/null
 
-	echo -n  Create directory for postmaster log
-	mkdir "$PGDATA/pg_log"
-	chown postgres:postgres "$PGDATA/pg_log"
-	chmod go-rwx "$PGDATA/pg_log"
+    echo -n  Create directory for postmaster log
+    mkdir "$PGDATA/pg_log"
+    chown postgres:postgres "$PGDATA/pg_log"
+    chmod go-rwx "$PGDATA/pg_log"
 
-	echo -n Are we okay?
-	if [ -f "$PGDATA/PG_VERSION" ]
-	then
-	    echo -n " [ OK ] "
-	else
-	    echo -n " [FAILED] "
-	    script_result=1
-	fi
-	echo
+    echo -n Are we okay?
+    if [ -f "$PGDATA/PG_VERSION" ]
+    then
+        echo -n " [ OK ] "
+    else
+        echo -n " [FAILED] "
+        script_result=1
+    fi
+    echo
+    fi
+}
+
+initdbtest () {
+    if [ -f "$PGDATA/PG_VERSION" ]
+    then
+        echo -n "Data directory is not empty!"
+        echo -n " [FAILED] "
+        echo
+        script_result=1
+    else
+        echo -n  -n "Initializing database: "
+    if [ ! -e "$PGDATA" -a ! -h "$PGDATA" ]
+    then
+        mkdir -p "$PGDATA" || exit 1
+        chown postgres:postgres "$PGDATA"
+        chmod go-rwx "$PGDATA"
+    fi
+    
+    echo -n  Clean up SELinux tagging for PGDATA
+    [ -x /sbin/restorecon ] && /sbin/restorecon "$PGDATA"
+
+    echo -n  Make sure the startup-time log file is OK, too
+    if [ ! -e "$PGLOG" -a ! -h "$PGLOG" ]
+    then
+        touch "$PGLOG" || exit 1
+        chown postgres:postgres "$PGLOG"
+        chmod go-rwx "$PGLOG"
+        [ -x /sbin/restorecon ] && /sbin/restorecon "$PGLOG"
+    fi
+
+    echo -n  Initialize the database
+    $SU -l postgres -c "/usr/bin/gdb --args $PGENGINE/initdb -d --pgdata='$PGDATA' --auth='ident'"
+
+    echo -n  Create directory for postmaster log
+    mkdir "$PGDATA/pg_log"
+    chown postgres:postgres "$PGDATA/pg_log"
+    chmod go-rwx "$PGDATA/pg_log"
+
+    echo -n Are we okay?
+    if [ -f "$PGDATA/PG_VERSION" ]
+    then
+        echo -n " [ OK ] "
+    else
+        echo -n " [FAILED] "
+        script_result=1
+    fi
+    echo
     fi
 }
 
 case "$1" in
   initdb)
-	initdb
-	;;
+    initdb
+    ;;
   *)
-	echo "Usage: $0 initdb"
-	exit 2
+    echo "Usage: $0 initdb"
+    # exit 2
 esac
 
-exit $script_result
+# exit $script_result
